#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 LVGL tiny_ttf 用的中文字体子集 rw1_font.c。

背景：LVGL 自带的 source_han_sans_sc_16_cjk 是“演示字体”，只包含一小撮
随机字符（见其生成注释），绝大多数常用汉字缺字 → 屏幕上显示成方块/乱码。
本脚本从 C:\\Windows\\Fonts\\simhei.ttf 裁一个只含“项目实际用到的字 + 常用字”
的子集 TTF，编译进固件，由 LVGL 的 tiny_ttf 运行时渲染，缺字问题即消失。

字集来源（自动扫描）：
  - ../server/server.py 里出现的非 ASCII 字符（AI 回复模板/活动标签）
  - ../device/main/*.c|*.h 里出现的非 ASCII 字符（界面文案）
  - 外加一批常用汉字 + 中文标点，给服务器文案微调留余量。

用法（任意有 fontTools 的 Python）：
    python gen_font.py
改完界面/服务器文案后重跑一次，再 idf.py build 即可。

输出文件 device/main/rw1_font.{c,h} 已被 .gitignore 排除（系统字体版权原因，
详见 NOTICE）——每个使用者在自己机器上跑本脚本生成。
"""
from __future__ import annotations

import glob
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC_FILES = (
    [os.path.join(ROOT, "server", "server.py")]
    + glob.glob(os.path.join(ROOT, "device", "main", "*.c"))
    + glob.glob(os.path.join(ROOT, "device", "main", "*.h"))
)
FONT_IN = r"C:\Windows\Fonts\simhei.ttf"
OUT_C = os.path.join(ROOT, "device", "main", "rw1_font.c")
OUT_H = os.path.join(ROOT, "device", "main", "rw1_font.h")

# 常用字 + 标点，给未来文案调整留余量（约 350 字，≈130KB 以内）
EXTRA = (
    "，。！？：；、（）《》“”‘’·—…％℃"
    "你好我是表盘发板小助手当前传感器读数合加速度正在进行动的是最近秒内约计步次"
    "摇晃试试把它某方向倾斜放平按即可向电脑服务器提问静置水平上下左右前后剧烈疑似"
    "跌落失重运动步行峰值检测到敲击状态怎么样谢谢同学老师任务完成交互课第一周开发"
    "显示屏幕连接失败无等待启动中数据发送接收响应请求正常异常断开通信网络地址端口"
    "超时空服务未请检查确认关闭浏览器刷新页面仪表实时推姿态曲线事件日志回答问题目"
    "需求实现流程闭环测试验证运行记录存储历史统计平均最大最断方差阈值触发判断识别"
    "分类算法模型人工能智大接口文档参数字段类型数值字符编码格式样式布局颜色字体"
    "大小写换滚按钮长按单击点击短按双击切换模式窗标签标内容文本图标箭头指示信号"
    "电源电量充电温度湿度光照距强弱快慢高低深浅宽窄厚薄远近少剩余足够完整缺少记录"
)


def collect_chars() -> set[str]:
    chars = set(EXTRA)
    for path in SRC_FILES:
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        for ch in text:
            if ord(ch) > 0x7F:
                chars.add(ch)
    return chars


def main() -> int:
    try:  # 控制台可能是 GBK，缺字符直接改 UTF-8 容错输出
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass
    if not os.path.exists(FONT_IN):
        print(f"font not found: {FONT_IN}", file=sys.stderr)
        return 1
    chars = collect_chars()
    unicodes = sorted({ord(c) for c in chars} | set(range(0x20, 0x7F)))

    opts = subset.Options()
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables += ["DSIG"]
    font = subset.load_font(FONT_IN, opts)
    subsetter = subset.Subsetter(opts)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    tmp_ttf = os.path.join(HERE, "_rw1_font.tmp.ttf")
    font.save(tmp_ttf)

    # 覆盖率自检：确认目标字符全部在子集 cmap 中
    # 覆盖率自检：板端源码里的每个非 ASCII 字符都必须被子集包含；
    # 仅服务器/仪表盘文案里的装饰字符（如 ✔）缺失只作警告。
    board_chars = set()
    for path in glob.glob(os.path.join(ROOT, "device", "main", "*.c")) + \
                glob.glob(os.path.join(ROOT, "device", "main", "*.h")):
        with open(path, encoding="utf-8", errors="replace") as fh:
            # 注释里的字符可能出现在字符串外，宁可多报不漏报：只挑字符串行
            for line in fh:
                if '"' in line and not line.lstrip().startswith(("*", "//", "/*")):
                    board_chars.update(c for c in line if ord(c) > 0x7F)
    check = TTFont(tmp_ttf)
    have = set()
    for table in check["cmap"].tables:
        have.update(table.cmap.keys())
    missing = sorted(c for c in unicodes if c not in have)
    hard = [c for c in missing if chr(c) in board_chars]
    size = os.path.getsize(tmp_ttf)
    print(f"subset chars={len(unicodes)} size={size/1024:.0f}KB "
          f"missing={len(missing)} (board-critical={len(hard)})")
    if missing:
        print("NOTE not-in-font (dashboard/browser only):",
              "".join(chr(c) for c in missing))
    if hard:
        print("MISSING ON BOARD:", "".join(chr(c) for c in hard), file=sys.stderr)

    with open(tmp_ttf, "rb") as fh:
        data = fh.read()
    os.remove(tmp_ttf)

    with open(OUT_H, "w", encoding="utf-8") as fh:
        fh.write(
            "/* Generated by rw1/tools/gen_font.py - do not edit by hand.\n"
            " * Subset of SimHei covering the UI/server vocabulary, for LVGL tiny_ttf. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            "extern const uint8_t rw1_font_ttf[];\n"
            "extern const unsigned int rw1_font_ttf_len;\n"
        )
    with open(OUT_C, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by rw1/tools/gen_font.py - do not edit by hand. */\n")
        fh.write('#include "rw1_font.h"\n\n')
        fh.write("const uint8_t rw1_font_ttf[] = {\n")
        for i in range(0, len(data), 20):
            fh.write(",".join(str(b) for b in data[i:i + 20]) + ",\n")
        fh.write("};\n\nconst unsigned int rw1_font_ttf_len = sizeof(rw1_font_ttf);\n")
    print(f"wrote {OUT_C}")
    return 1 if hard else 0


if __name__ == "__main__":
    sys.exit(main())
